http_port: 3000

# 日志配置
log_level: debug # 日志级别 info, debug, warn, error, trace, off
save_log: false # 是否保存日志
log_file: logs/radar_detector.log # 日志文件

# redis配置
main_redis:
  ip: 127.0.0.1
  port: 6380
  auth: lktspacE123
  db: 1

# postgres配置
postgres:
  ip: 127.0.0.1
  port: 5432
  db: radar_db
  admin: radar
  password: radar123
  min_connections: 1
  max_connections: 100
  sqlx_logging: false
